### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by roxxel** [remore-chat/Remore#12]
- [x] Voice channels
- [x] Text channels
- [x] Noise reducer
- [x] Privilege key
- [x] Better or same voice quality as TeamSpeak    
- [x] Manage server info
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] Avatars
- [ ] Emoji picker
### After this point project is already usable, but not ready for production usage
- [ ] User roles
- [ ] Managing channels
- [ ] #14
- [ ] Server sided plugins
- [ ] Client sided plugins
- [ ] Direct calls (Can be done by creating another private channel for 2 people)

### After desktop client fully completed: Create mobile application
